# Writing raster images






We have covered a few processing techniques in this class, but one of the most important is to understand how to write image data.

In previous tutorials we have covered the fundamental structure of an image. Therefore, today we will build on this concept, creating a very basic data structure manually, and then writing it out to a file. 

First, let us import `numpy` and `rasterio`, as we require these to specify the data structure and then export the data as a raster. 

In [14]:
# Example
import numpy as np
import rasterio 

Next, let us try create the basic data structure for our image. 

This is pretty much as simple as a structure can be - So a 3x3 matrix of values, converted to a `numpy` array:

In [11]:
# Example
array = np.array(
    [
        [1,0,1],
        [0,1,0],
        [1,0,1],
    ]   
)
print(array)

[[1 0 1]
 [0 1 0]
 [1 0 1]]


Before we write this to a file, we need to create/update (the dreaded) metadata. 

As covered in previous classes, metadata is essential to inform other software programs how to display this data, e.g. your preferred GIS.

(NB. Some of you have been trying to utilize images with no associated metadata, so watch out for that.) 

In [12]:
# Example
profile = {
    'width': array.shape[0],  #width of the data/image
    'height': array.shape[1], #height of the data/image
    'dtype': rasterio.uint8,  #data type of the data/image
    'count': 1,               #layer count of the data/image
    'compress': 'lzw'         #compression type
}

Now we can try write out example image data structure. 

We can use a writing example from the `rasterio` documentation, here: https://rasterio.readthedocs.io/en/latest/topics/writing.html 

In [13]:
# Example
with rasterio.open('writing_raster_images_example.tif', 'w', **profile) as dst:
    dst.write(array.astype(rasterio.uint8), 1)

## Exercise

Can you create a chessboard-style image (alternating white and black squares), for an image with dimensions 8x8?

This exercise will help reinforce your understanding of how an image is created, stored and written. 

In [3]:
# Enter your attempt below


C:\Users\eoughton\Anaconda3\envs\sia\Lib\site-packages\rasterio\__init__.py:230: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix be returned.
  s = writer(path, mode, driver=driver,


Can you create and export a .tif file with alternating white and black columns, for dimensions 8x12? 

Please manually specify your metadata width and height values.

In [15]:
# Enter your attempt below
