# Writing raster images






We have covered a few processing techniques in this class, but one of the most important is to understand how to write image data.

In previous tutorials we have covered the fundamental structure of an image. Therefore, today we will build on this concept, creating a very basic data structure manually, and then writing it out to a file. 

First, let's import `numpy` and `rasterio`, as we require these to specify the data structure and then export the data as a raster. 

In [1]:
# Example
import numpy as np
import rasterio 

Next, let's try create a basic data structure for our image. 

This is pretty much as simple as a structure can be - So a 3x3 matrix of values, converted to a `numpy` array:

In [2]:
# Example
array = np.array(
    [
        [1,1,1],
        [1,1,1],
        [1,1,1],
    ]   
)
print(array)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


Now before we write this to a file, we need to create/update (the dreaded) metadata. 

As covered in previous classes, metadata is essential to inform other software programs how to display this data, e.g. your preferred GIS.

In [3]:
# Example

profile = {
    'width': array.shape[0],  #width of the data/image
    'height': array.shape[1], #height of the data/image
    'dtype': rasterio.uint8,  #data type of the data/image
    'count': 1,               #layer count of the data/image
    'compress': 'lzw'         #compression type
}

Now we can try write out example image data structure. 

Let's use an writing example from the `rasterio` documentation, here: https://rasterio.readthedocs.io/en/latest/topics/writing.html 

In [4]:
# Example

# First, let's register GDAL format drivers and configuration options with a
# context manager.
with rasterio.Env():

    # For the new file's profile, let's us the metadata we specified
    profile = profile
    
    with rasterio.open('example.tif', 'w', **profile) as dst:
        dst.write(array.astype(rasterio.uint8), 1)

D:\Anaconda\envs\sia\lib\site-packages\rasterio\__init__.py:230: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix be returned.
  s = writer(path, mode, driver=driver,


## Exercise

Can you create a chessboard-style image (alternating white and black squares), for an image with dimensions 8x8?

This exercise will help reinforce your understanding of how an image is created, stored and written. 

In [5]:
# Enter your attempt below


Once complete, you can begin reviewing this week's assignment and make a start on your submission.